.github/workflows/linters.yml

The PR removes the "cron: '0 6 * * *'" schedule from the linters workflow.

Remove cron schedule from linters GH workflow

---

.github/workflows/sanity.yml
changelogs/fragments/20230823-update-ci-sanity-test-matrix.yaml

The milestone and devel branches of ansible no longer support python 3.9. This PR adds milestone/python 3.9 to `matrix_exclude` in the sanity test Github Actions workflow.
- Bugfix Pull Request

Exclude python 3.9 for milestone in sanity test matrix

---

README.md
playbooks/VALIDATE_DEPLOYMENT.md
playbooks/VMSS_MIGRATE.md
playbooks/WEBAPP.md
playbooks/WEBAPP_CONTAINER.md
playbooks/webapp.yml
playbooks/webapp_container.yml

add documentation for collection playbooks `vmss_migrate.yml`, `webapp.yml` and `webapp_container.yml`

Document collection playbooks

---

changelogs/fragments/20240305-update_postgresql_example.yml
roles/azure_manage_postgresql/README.md

The current example doesn't work since it's missing the name of the postgresql server and the disk size is invalid according to azure.

Update the example

---

changelogs/fragments/role_arg_specs.yaml
roles/azure_load_balancer_with_public_ip/meta/argument_specs.yml
roles/azure_load_balancer_with_public_ip/tasks/main.yml
roles/azure_manage_network_interface/meta/argument_specs.yml
roles/azure_manage_network_interface/tasks/main.yml
roles/azure_manage_networking_stack/meta/argument_specs.yml
roles/azure_manage_postgresql/meta/argument_specs.yml
roles/azure_manage_postgresql/tasks/main.yml
roles/azure_manage_resource_group/meta/argument_specs.yml
roles/azure_manage_resource_group/tasks/main.yml
roles/azure_manage_security_group/meta/argument_specs.yml
roles/azure_manage_security_group/tasks/main.yml
roles/azure_virtual_machine_with_public_ip/meta/argument_specs.yml
roles/azure_virtual_machine_with_public_ip/tasks/main.yml

This PR adds argument_specs.yml to the roles to enable validation of arguments.
This aligns with https://github.com/ansible-collections/cloud-content-handbook/blob/main/Roles-arguments_validation.md and https://github.com/redhat-cop/automation-good-practices/tree/main/roles#argument-validation

Add arguments_specs to roles

---

README.md
changelogs/fragments/20240320-relative-links.yml
roles/azure_load_balancer_with_public_ip/README.md
roles/azure_manage_network_interface/README.md
roles/azure_manage_networking_stack/README.md
roles/azure_manage_postgresql/README.md
roles/azure_manage_resource_group/README.md
roles/azure_manage_security_group/README.md
roles/azure_virtual_machine_with_public_ip/README.md

Updating the docs to use relative links so that when imported into automation hub it doesn't point back to github.  This can be an issue when examples or variables have been updated on github but hasn't been pushed to automation hub yet.

Update docs to use relative links

---

.gitignore
changelogs/fragments/20240319-Integration-tests.yml
playbooks/webapp_container.yml
roles/azure_load_balancer_with_public_ip/tasks/delete.yml
roles/azure_manage_security_group/README.md
roles/azure_manage_security_group/tasks/delete.yml
roles/azure_manage_security_group/tasks/detach_from_nic.yml
roles/azure_manage_security_group/tasks/detach_from_subnet.yml
roles/azure_manage_security_group/tasks/main.yml
roles/azure_manage_security_group/tasks/remove_rules.yml
tests/integration/targets/test_azure_load_balancer_with_public_ip/aliases
tests/integration/targets/test_azure_load_balancer_with_public_ip/defaults/main.yml
tests/integration/targets/test_azure_load_balancer_with_public_ip/tasks/main.yml
tests/integration/targets/test_azure_manage_network_interface/aliases
tests/integration/targets/test_azure_manage_network_interface/defaults/main.yml
tests/integration/targets/test_azure_manage_network_interface/tasks/main.yml
tests/integration/targets/test_azure_manage_security_group/aliases
tests/integration/targets/test_azure_manage_security_group/defaults/main.yml
tests/integration/targets/test_azure_manage_security_group/tasks/main.yml

Updates to abikouo work on Integration tests.
These now pass when run with ansible-test integration

Integration tests

---

.github/workflows/linters.yml
README.md
changelogs/fragments/20240508-github-absolute-links.yml
roles/azure_load_balancer_with_public_ip/README.md
roles/azure_manage_network_interface/README.md
roles/azure_manage_networking_stack/README.md
roles/azure_manage_postgresql/README.md
roles/azure_manage_resource_group/README.md
roles/azure_manage_security_group/README.md
roles/azure_virtual_machine_with_public_ip/README.md

This reverts commit f3e2d3d69415e59ccb969cb68d0940cb342ecb9e. 
README files can't use links with relative path, because the hierarchy is not the same in AAP. This commit change back to use main branch full path.

Revert "Update docs to use relative links"

---

changelogs/fragments/20240508-azure_manage_resource_group.yml
roles/azure_manage_resource_group/tasks/delete.yml

Add a timeout (as a temporary solution) in the delete task of the azure_manage_resource_group role.
Fix for this bug - https://issues.redhat.com/browse/ACA-1498
In the future we should consider backoff logic (retries) in the delete code.

Add a timeout in the delete task in azure_manage_resource_group role

---

roles/azure_manage_resource_group/tasks/delete.yml
tests/integration/targets/test_azure_manage_resource_group/aliases
tests/integration/targets/test_azure_manage_resource_group/defaults/main.yml
tests/integration/targets/test_azure_manage_resource_group/tasks/main.yml

Added integration test for test_azure_manage_resource_group role.
This is the first PR for the positive scenario without using "locking":
- creation and deletion of resource group

Added integration for test_azure_manage_resource_group role

---

changelogs/fragments/20240521-azure_resource_groups_delete.yml
roles/azure_manage_resource_group/tasks/delete.yml

In some cases, the resource group can't be deleted immediately. 
We need to wait until all resources inside it are completely destroyed. 
Add retries with a 5-second delay, with a maximum of 40 retries.

Add retries to Resource Group deletion

---

tests/integration/targets/test_azure_manage_resource_group/tasks/main.yml

The permissions issue is solved, so I added negative integration test for test_azure_manage_resource_group role.
This is the second PR (for the negative scenario with using "locking"):
- creation and deletion of resource group

Added negative integration test for test_azure_manage_resource_group role

---

changelogs/fragments/20240602-azure_vm_with_public_ip_create.yml
roles/azure_virtual_machine_with_public_ip/README.md
roles/azure_virtual_machine_with_public_ip/meta/argument_specs.yml
roles/azure_virtual_machine_with_public_ip/tasks/create.yml
roles/azure_virtual_machine_with_public_ip/tasks/delete.yml
tests/integration/targets/test_azure_virtual_machine_with_public_ip/aliases
tests/integration/targets/test_azure_virtual_machine_with_public_ip/defaults/main.yml
tests/integration/targets/test_azure_virtual_machine_with_public_ip/tasks/ensure_no_vm_found.yml
tests/integration/targets/test_azure_virtual_machine_with_public_ip/tasks/main.yml

For azure_virtual_machine_with_public_ip role:
- Added virtual network auto-creation if no virtual network found
- Added simple test with default create/delete options to verify changes

Added virtual network auto-creation if no virtual network found for azure_virtual_machine_with_public_ip role

---

changelogs/fragments/20240613-bug_fixes.yaml
roles/azure_load_balancer_with_public_ip/tasks/create.yml
roles/azure_manage_networking_stack/tasks/create.yml
roles/azure_manage_postgresql/tasks/create.yml
roles/azure_virtual_machine_with_public_ip/README.md
roles/azure_virtual_machine_with_public_ip/tasks/create.yml
roles/azure_virtual_machine_with_public_ip/tasks/delete.yml
roles/azure_virtual_machine_with_public_ip/tasks/main.yml

Changes:
- [ACA-1634](https://issues.redhat.com/browse/ACA-1634): Added missed argument 'started: true' to the 'Power On VM' task in azure_virtual_machine_with_public_ip role
- [ACA-1580](https://issues.redhat.com/browse/ACA-1580): Updated README with proper role's variables description for azure_virtual_machine_with_public_ip role
- [ACA-1633](https://issues.redhat.com/browse/ACA-1633): Fixed undefined variables issue for azure_virtual_machine_with_public_ip role
- [ACA-1635](https://issues.redhat.com/browse/ACA-1635): Fixed azure_manage_resource_group_tags value for the new resource group creation by role

Bug fixes of the azure roles

---

changelogs/fragments/20240617-azure_manage_postgresql_readme.yml
roles/azure_manage_postgresql/README.md

Fixed bug:
1. Removed duplicated var from README file of azure_manage_postgresql role (https://issues.redhat.com/browse/ACA-1637)

Bug fix: Removed duplicated var from README file of azure_manage_postgresql role

---

changelogs/fragments/20240617-azure_manage_postgresql_create.yml
roles/azure_manage_postgresql/tasks/create.yml
tests/integration/targets/test_azure_manage_postgresql/aliases
tests/integration/targets/test_azure_manage_postgresql/defaults/main.yml
tests/integration/targets/test_azure_manage_postgresql/tasks/create_and_delete_postgresql.yml
tests/integration/targets/test_azure_manage_postgresql/tasks/main.yml

Added integration test for  azure_manage_postgresql role.
Two scenarios tested:
1. Test azure_manage_postgresql role with pre-created Resource group
2. Test azure_manage_postgresql role with create/delete Resource group option
Fixed bug:
1. Fixed undefined vars in the create.yml file of azure_manage_postgresql role (https://issues.redhat.com/browse/ACA-1599)

Added integration test for  azure_manage_postgresql role

---

tests/integration/targets/test_azure_manage_postgresql/defaults/main.yml
tests/integration/targets/test_azure_manage_postgresql/tasks/main.yml

This change is done in order to avoid having hardcoded "password like" string in the repository.
Avoid "Potential data leak" reports from security reviewing service

Generate random password instead of hardcoded

---

changelogs/fragments/20240721-azure_manage_postgresql.yml
roles/azure_manage_postgresql/README.md
tests/integration/targets/test_azure_manage_postgresql/defaults/main.yml
tests/integration/targets/test_azure_manage_postgresql/tasks/create_and_delete_postgresql.yml

Removing SKU tier, capacity, and size parameters from role and test

ACA-1602: Removing SKU tier, capacity and size parameters from role and test

---

changelogs/fragments/20240723-test_azure_load_balencer_with_public_ip.yml
tests/integration/targets/test_azure_load_balancer_with_public_ip/tasks/main.yml

Adding alwayes statement to the first block in test_azure_load_balancer_with_public_ip test to verify the removal of load balancer and public IP resources

ACA-1640 load balancer with public ip

---

changelogs/fragments/20240814-azure_manage_resurce_group.yml
roles/azure_manage_resource_group/tasks/delete.yml

Updating retries count to be 20 from 40 in the Delete resource group task in order to shorten the time the user waits before the task fails

ACA-1515 Updating retries count to be 20 from 40

---

changelogs/fragments/20241109-azure_manage_postgresql.yml
roles/azure_manage_postgresql/tasks/create.yml
roles/azure_manage_postgresql/tasks/delete.yml

Fixed bugs:
- Fixed undefined var issue in the create.yml file of azure_manage_postgresql role (https://issues.redhat.com/browse/ACA-1839)
- Fixed undefined var issue in the delete.yml file of azure_manage_postgresql role (https://issues.redhat.com/browse/ACA-1838)

Fixed undefined var issues in the create.yml and delete.yml files of azure_manage_postgresql role

---

.ansible-lint
changelogs/fragments/20250129-azure_virtual_machine_with_public_ip.yml
roles/azure_manage_snapshot/README.md
roles/azure_manage_snapshot/defaults/main.yml
roles/azure_manage_snapshot/meta/argument_specs.yml
roles/azure_manage_snapshot/tasks/create.yml
roles/azure_manage_snapshot/tasks/delete.yml
roles/azure_manage_snapshot/tasks/main.yml
roles/azure_manage_snapshot/tasks/restore.yml
roles/azure_virtual_machine_with_public_ip/README.md
roles/azure_virtual_machine_with_public_ip/meta/argument_specs.yml
roles/azure_virtual_machine_with_public_ip/tasks/create.yml
tests/integration/requirements.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/aliases
tests/integration/targets/azure_ops_test_azure_manage_snapshot/defaults/main.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/after_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/before_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/create_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/delete_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/main.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/restore_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/setup.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/teardown.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/validate_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/validate_vm_from_snapshot.yml
tests/integration/targets/azure_ops_test_azure_manage_snapshot/tasks/vm_from_snapshot.yml

New role azure_manage_snapshot will help in creating, restoring and deleting snapshots.

Add new azure_manage_snapshot role
